# Generated by Django 3.2.25 on 2025-10-05 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Dr. Shahan', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.CharField(blank=True, max_length=250)),
                ('achievements', models.TextField(blank=True)),
                ('services', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('site_domain', models.CharField(blank=True, max_length=150)),
                ('is_live', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('consent_to_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='portfolio.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cases/%Y/%m/')),
                ('image_type', models.CharField(choices=[('PRE', 'Pre-op'), ('POST', 'Post-op')], max_length=4)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.patientcase')),
            ],
        ),
        migrations.CreateModel(
            name='BeforeAfterPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='portfolio.patientcase')),
                ('post_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_post', to='portfolio.caseimage')),
                ('pre_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_pre', to='portfolio.caseimage')),
            ],
        ),
    ]
